[workspace]
authors = ["j-bac <jo.bac@live.fr>"]
channels = ["conda-forge","bioconda"]
name = "norkin_organoid"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<=3.11"
tmux = ">=3.5,<4"

[environments]
norkin-organoid = ["norkin-organoid"]

[feature.norkin-organoid.tasks]
add-kernel = "python -m ipykernel install --user --name norkin_organoid --display-name 'Python (norkin_organoid)'"
fix-genomeinfodb = 'R --vanilla -e "BiocManager::install(\"GenomeInfoDbData\")"'

[feature.norkin-organoid.dependencies]
spatialdata = ">=0.4.0,<0.5"
spatialdata-io = ">=0.2.0,<0.3"
spatialdata-plot = ">=0.2.10,<0.3"
ipykernel = ">=6.29.5,<7"
scanpy = ">=1.11.2,<2"
r-seurat = { version = ">=5.3.0,<6", channel = "conda-forge" }
"r-this.path" = { version = ">=2.7.0,<3", channel = "conda-forge" }
bioconductor-s4vectors = { version = ">=0.40.2,<0.45", channel = "bioconda" }
bioconductor-singlecellexperiment = { version = ">=1.24.0,<2", channel = "bioconda" }
bioconductor-genomeinfodbdata = { version = ">=1.2.11,<2", channel = "bioconda" }
anndata2ri = { version = ">=1.3.2,<2", channel = "bioconda" }
bioconductor-genomeinfodb = { version = ">=1.38.1,<2", channel = "bioconda" }
r-biocmanager = { version = ">=1.30.26,<2", channel = "conda-forge" }
r-readr = ">=2.1.5,<3"
r-hdf5r = ">=1.3.12,<2"
scvi-tools = ">=1.3.2,<2"
snakemake = ">=9.8.0,<10"
