base_dir: "/work/PRTNR/CHUV/DIR/rgottar1/spatial/data/norkin_organoid/"
data_dir: "data/"
scratch_dir: "workflow/scratch/"
scripts_dir: "workflow/scripts/"
results_dir: "results/"
figures_dir: "figures/"
log_dir: "log/"
markers_dir: "data/markers/"

xenium_metadata_dir: "data/xenium/metadata/"
xenium_raw_data_dir: "data/xenium/raw/"
xenium_count_correction_dir: "data/xenium/processed/count_correction/"
xenium_processed_dir: "data/xenium/processed/segmentation/"
xenium_std_seurat_analysis_dir: "data/xenium/processed/std_seurat_analysis/"
xenium_cell_type_annotation_dir: "data/xenium/processed/cell_type_annotation/"

scrnaseq_processed_dir: "data/scRNAseq/processed/"
scrnaseq_references_dir: "data/scRNAseq/processed/references/"

scrnaseq_reference_GSE178341_seurat: "data/scRNAseq/processed/references/GEO_GSE178341/GSE178341_seurat.rds"
scrnaseq_reference_GSE236581_seurat: "data/scRNAseq/processed/references/GEO_GSE236581/GSE236581_seurat.rds"
scrnaseq_reference_marteau_seurat: "data/scRNAseq/processed/references/Marteau2024/core_atlas-adata_subsampled.rds"

